//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameThatWrap.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comment_Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
        public string Author { get; set; }
        public string article_id { get; set; }
    }
}
