//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameThatWrap.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrap
    {
        public int wrap_Id { get; set; }
        public string colorway { get; set; }
        public string brand { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
        public string author { get; set; }
        public string img_name { get; set; }
    }
}
