//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameThatWrap.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrap
    {
        public int WrapID { get; set; }
        public string Colorway { get; set; }
        public string Brand { get; set; }
        public string ImgName { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public Nullable<System.DateTime> Date_updated { get; set; }
        public string Author { get; set; }
    }
}
